import '../model/content.dart';
import '../model/library.dart';

List<lib> iconsList = [
  lib("الناس", "assets/pepole.png", "yes", [
    Content("يد ", "assets/hand.png", "yes", "", "", "yes"),
    Content("غضب ", "assets/angry.png", "yes", "", "", "yes"),
    Content("اتصال ", "assets/phone-call.png", "yes", "", "", "yes"),
    Content("طوارئ", "assets/ambulance.png", "yes", "", "", "yes"),
    Content("بكاء ", "assets/crying.png", "yes", "", "", "yes"),
    Content("طفش ", "assets/bored.png", "yes", "", "", "yes"),
    Content("ضحك", "assets/laughter.png", "yes", "", "", "yes"),
    Content("الم ", "assets/pain.png", "yes", "", "", "yes"),
    Content("حر", "assets/heat.png", "yes", "", "", "yes"),
    Content("نائم ", "assets/sleep.png", "yes", "", "", "yes"),
    Content("مستيقظ ", "assets/awake.png", "yes", "", "", "yes"),
    Content("طفل", "assets/baby.png", "yes", "", "", "yes"),
    Content("اخت ", "assets/sister.png", "yes", "", "", "yes"),
    Content("ام ", "assets/mother.png", "yes", "", "", "yes"),
    Content("اخ", "assets/brother.png", "yes", "", "", "yes"),
    Content("اب ", "assets/father.png", "yes", "", "", "yes"),
    Content("حواس", "assets/human-brian.png", "yes", "", "", "yes"),
    Content("قوي ", "assets/strong.png", "yes", "", "", "yes"),
    Content("شعر", "assets/hair.png", "yes", "", "", "yes"),
    Content("اسمي ", "assets/name.png", "yes", "", "", "yes"),
    Content("جرح ", "assets/injury.png", "yes", "", "", "yes"),
    Content("قدم", "assets/foot.png", "yes", "", "", "yes"),
    Content("ذراع ", "assets/arm.png", "yes", "", "", "yes"),
    Content("برد", "assets/cold.png", "yes", "", "", "yes"),
    Content("عين", "assets/eye.png", "yes", "", "", "yes"),
    Content("اذن ", "assets/ear.png", "yes", "", "", "yes"),
    Content("لسان ", "assets/tongue.png", "yes", "", "", "yes"),
  ]),
  lib("المدارس", "assets/school.png", "yes", [
    Content("حاسبة ", "assets/calculator.png", "yes", "", "", "yes"),
    Content("زائد ", "assets/add.png", "yes", "", "", "yes"),
    Content("ناقص ", "assets/remove.png", "yes", "", "", "yes"),
    Content("نصف ", "assets/half.png", "yes", "", "", "yes"),
    Content("يساوي ", "assets/equal.png", "yes", "", "", "yes"),
    Content("قسمة ", "assets/divide.png", "yes", "", "", "yes"),
    Content("رقم ", "assets/numbers.png", "yes", "", "", "yes"),
    Content("الوان ", "assets/colors.png", "yes", "", "", "yes"),
    Content("فواصل ", "assets/comma.png", "yes", "", "", "yes"),
    Content("رتب ", "assets/arrange.png", "yes", "", "", "yes"),
  ]),
  lib("الملابس", "assets/clothes.png", "yes", [
    Content("تغيير الملابس", "assets/change.png", "yes", "", "", "yes"),
    Content("فتح الزر  ", "assets/button.png", "yes", "", "", "yes"),
    Content("اغلاق الزر", "assets/button (1).png", "yes", "", "", "yes"),
    Content("كبير جدا", "assets/loose.png", "yes", "", "", "yes"),
    Content("ضيق جدا", "assets/TightJeans.png", "yes", "", "", "yes"),
    Content("متسخ", "assets/dirty.png", "yes", "", "", "yes"),
    Content("ارتداء الملابس", "assets/getDressed.png", "yes", "", "", "yes"),
    Content("اغلاق السحاب", "assets/zipper.png", "yes", "", "", "yes"),
    Content("فتح السحاب", "assets/unzip.png", "yes", "", "", "yes"),
    Content("بنطال مبلل  ", "assets/wetpants.png", "yes", "", "", "yes"),
    Content("ملابس داخلية", "assets/underwear.png", "yes", "", "", "yes"),
    Content("شراب", "assets/socks.png", "yes", "", "", "yes"),
    Content("حذاء", "assets/shoe.png", "yes", "", "", "yes"),
    Content("حذاء رياضي", "assets/sneakers.png", "yes", "", "", "yes"),
    Content("ملابس  ", "assets/clothes.png", "yes", "", "", "yes"),
    Content("محفظة", "assets/wallet.png", "yes", "", "", "yes"),
    Content("ساعة", "assets/watch.png", "yes", "", "", "yes"),
    Content("أقراط أذن ", "assets/earings.png", "yes", "", "", "yes"),
    Content("نظارات ", "assets/glasses.png", "yes", "", "", "yes"),
    Content("منديل يد ", "assets/tissue.png", "yes", "", "", "yes"),
    Content("حقيبة ظهر ", "assets/backpack.png", "yes", "", "", "yes"),
  ]),
  lib("الأماكن", "assets/place.png", "yes", [
    Content("مدرسة ", "assets/school-bus.png", "yes", "", "", "yes"),
    Content("منزل ", "assets/home.png", "yes", "", "", "yes"),
    Content("مستشفى", "assets/hospital.png", "yes", "", "", "yes"),
    Content("مكتبة ", "assets/library (1).png", "yes", "", "", "yes"),
    Content("غرفة النوم ", "assets/bedroom.png", "yes", "", "", "yes"),
    Content("حمام", "assets/public-toilet.png", "yes", "", "", "yes"),
    Content("المطبخ ", "assets/kitchen.png", "yes", "", "", "yes"),
    Content("جنوب ", "assets/direction.png", "yes", "", "", "yes"),
    Content("شرق", "assets/west.png", "yes", "", "", "yes"),
    Content("غرب ", "assets/east.png", "yes", "", "", "yes"),
    Content("شمال ", "assets/direction (1).png", "yes", "", "", "yes"),
    Content("الطابق العلوي", "assets/upstairs.png", "yes", "", "", "yes"),
    Content("الطابق السفلي", "assets/downstairs.png", "yes", "", "", "yes"),
  ]),
  lib("عائلة", "assets/family/0.jpg", "yes", [
    Content("طفل", "assets/family/1.png", "yes", "", "", "yes"),
    Content("ولد", "assets/family/2.png", "yes", "", "", "yes"),
    Content("اولاد", "assets/family/3.png", "yes", "", "", "yes"),
    Content("عروس", "assets/family/4.png", "yes", "", "", "yes"),
    Content("أخ", "assets/family/5.png", "yes", "", "", "yes"),
    Content("شيخ", "assets/family/6.jpg", "yes", "", "", "yes"),
    Content("اطفال", "assets/family/7.png", "yes", "", "", "yes"),
    Content("عائلة", "assets/family/8.jpg", "yes", "", "", "yes"),
    Content("بنت", "assets/family/9.png", "yes", "", "", "yes"),
    Content("جد", "assets/family/10.png", "yes", "", "", "yes"),
    Content("جدة", "assets/family/11.png", "yes", "", "", "yes"),
    Content("انا", "assets/family/12.png", "yes", "", "", "yes"),
  ]),
  lib("الوان", "assets/colors-m/0.png", "yes", [
    Content("اسود", "assets/colors-m/1.png", "yes", "", "", "yes"),
    Content("ازرق", "assets/colors-m/2.png", "yes", "", "", "yes"),
    Content("اخضر", "assets/colors-m/3.png", "yes", "", "", "yes"),
    Content("بنفسجي", "assets/colors-m/4.png", "yes", "", "", "yes"),
    Content("احمر", "assets/colors-m/5.png", "yes", "", "", "yes"),
    Content("ابيض", "assets/colors-m/6.png", "yes", "", "", "yes"),
    Content("اصفر", "assets/colors-m/7.png", "yes", "", "", "yes"),
  ]),
  lib("الجسم", "assets/body/0.png", "yes", [
    Content("كعب", "assets/body/1.png", "yes", "", "", "yes"),
    Content("لسان", "assets/body/2.png", "yes", "", "", "yes"),
    Content("ذراع", "assets/body/3.png", "yes", "", "", "yes"),
    Content("عدسة", "assets/body/4.png", "yes", "", "", "yes"),
    Content("أصابع القدم", "assets/body/5.png", "yes", "", "", "yes"),
    Content("اسنان", "assets/body/6.png", "yes", "", "", "yes"),
    Content("كتف", "assets/body/7.png", "yes", "", "", "yes"),
    Content("رقبة", "assets/body/8.png", "yes", "", "", "yes"),
  ]),
  lib("منزل", "assets/tools/0.jpg", "yes", [
    Content("سرير أطفال", "assets/tools/2.png", "yes", "", "", "yes"),
    Content("سرير", "assets/tools/3.png", "yes", "", "", "yes"),
    Content("غرفة نوم", "assets/tools/4.png", "yes", "", "", "yes"),
    Content("سلة مهملات", "assets/tools/5.png", "yes", "", "", "yes"),
    Content("برغي", "assets/tools/6.png", "yes", "", "", "yes"),
    Content("كرسي", "assets/tools/7.png", "yes", "", "", "yes"),
    Content("مجموعة ادراج", "assets/tools/8.png", "yes", "", "", "yes"),
    //  Content("سرير خفيف", "assets/tools/9.png", "yes", "", "", "yes"),
    Content("أريكة", "assets/tools/10.png", "yes", "", "", "yes"),
    Content("اجهزة تجكم ", "assets/tools/1.jpg", "yes", "", "", "yes"),
    Content("غطاء", "assets/tools/11.png", "yes", "", "", "yes"),
    Content("خزانة", "assets/tools/12.png", "yes", "", "", "yes"),
    Content("مفتاح", "assets/tools/13.jpg", "yes", "", "", "yes"),
    Content("ممسحة", "assets/tools/14.png", "yes", "", "", "yes"),
    Content("مشبك", "assets/tools/16.png", "yes", "", "", "yes"),
    Content("صورة", "assets/tools/17.png", "yes", "", "", "yes"),
    Content("دبوس", "assets/tools/18.png", "yes", "", "", "yes"),
    Content("مقعد", "assets/tools/19.png", "yes", "", "", "yes"),
    Content(" شباك", "assets/tools/20.png", "yes", "", "", "yes"),
  ]),
  lib("الحيوانات", "assets/Animall/0.png", "yes", [
    Content("حمار", "assets/Animall/18.jpg", "yes", "", "", "yes"),
    Content("ذئب", "assets/Animall/17.jpg", "yes", "", "", "yes"),
    Content("ثعبان", "assets/Animall/13.png", "yes", "", "", "yes"),
    Content("نمر ", "assets/Animall/16.png", "yes", "", "", "yes"),
    Content("طاووس", "assets/Animall/15.jpg", "yes", "", "", "yes"),
    Content("فأر", "assets/Animall/22.png", "yes", "", "", "yes"),
    Content("راما", "assets/Animall/12.png", "yes", "", "", "yes"),
    Content("سلحفاة", "assets/Animall/14.png", "yes", "", "", "yes"),
    Content("فيل", "assets/Animall/21.jpg", "yes", "", "", "yes"),
    Content("خفاش", "assets/Animall/20.png", "yes", "", "", "yes"),
    Content("بطة", "assets/Animall/19.png", "yes", "", "", "yes"),
    Content("دب", "assets/Animall/1.jpg", "yes", "", "", "yes"),
    Content("عصفور", "assets/Animall/2.png", "yes", "", "", "yes"),
    Content("قطة", "assets/Animall/3.png", "yes", "", "", "yes"),
    Content("دجاج", "assets/Animall/4.png", "yes", "", "", "yes"),
    Content("بقرة", "assets/Animall/5.jpg", "yes", "", "", "yes"),
    Content("غراب", "assets/Animall/6.jpg", "yes", "", "", "yes"),
    Content("غزال", "assets/Animall/7.png", "yes", "", "", "yes"),
    Content("ديناصور", "assets/Animall/8.jpg", "yes", "", "", "yes"),
    Content("ماعز", "assets/Animall/9.png", "yes", "", "", "yes"),
    Content("كلب", "assets/Animall/10.png", "yes", "", "", "yes"),
    Content("ارنب", "assets/Animall/11.png", "yes", "", "", "yes"),
  ]),
  lib("الطعام", "assets/food/veg.png", "yes", [
    Content("خضروات", "assets/food/veg.png", "yes", "", "", "yes"),
    Content("طماطم", "assets/food/tomato.png", "yes", "", "", "yes"),
    Content("فراولة", "assets/food/strawbrry.png", "yes", "", "", "yes"),
    Content("قرع", "assets/food/pumpkin.png", "yes", "", "", "yes"),
    Content("بطاطس مقلي", "assets/food/potatoes.jpg", "yes", "", "", "yes"),
    Content("بيتزا", "assets/food/pizza.png", "yes", "", "", "yes"),
    Content("كمثرى", "assets/food/pear.png", "yes", "", "", "yes"),
    Content("فطر", "assets/food/mushroom.jpg", "yes", "", "", "yes"),
    Content("نعناع", "assets/food/mint.png", "yes", "", "", "yes"),
    Content("حليب", "assets/food/milk.png", "yes", "", "", "yes"),
    Content("غداء", "assets/food/lunch.jpg", "yes", "", "", "yes"),
    Content("ملفوف", "assets/food/lettuce.jpg", "yes", "", "", "yes"),
    Content("مانجو", "assets/food/mango.jpg", "yes", "", "", "yes"),
    Content("عنب", "assets/food/grape.png", "yes", "", "", "yes"),
    Content("فواكهه", "assets/food/fruits.png", "yes", "", "", "yes"),
    Content("فلفل", "assets/food/hot-pepper.png", "yes", "", "", "yes"),
    Content("آيسكريم", "assets/food/icecream.jpg", "yes", "", "", "yes"),
    Content("كيوي", "assets/food/ki.png", "yes", "", "", "yes"),
  ]),
  lib("اماكن", "assets/Places/0.png", "yes", [
    Content("مكة ", "assets/Places/mecca.jpg", "yes", "", "", "yes"),
    Content("منى ", "assets/Places/mina.png", "yes", "", "", "yes"),
    Content("مزدلفة ", "assets/Places/Muzdalifah.png", "yes", "", "", "yes"),
    Content("مركز تجاري", "assets/Places/shopping-center.png", "yes", "", "",
        "yes"),
    Content("دورة مياه - رجال", "assets/Places/Toilet-man.png", "yes", "", "",
        "yes"),
    Content("دورة مياه - نساء ", "assets/Places/Toilet-w.png", "yes", "", "",
        "yes"),
    Content(
        "سوبر ماركت  ", "assets/Places/Supermarket.png", "yes", "", "", "yes"),
  ]),
  lib("ملابس", "assets/clothes/0.png", "yes", [
    Content("تنورة ", "assets/clothes/skirt-m.png", "yes", "", "", "yes"),
    Content(" عباية ", "assets/clothes/abaya.png", "yes", "", "", "yes"),
    Content(" شورت ", "assets/clothes/shorts.png", "yes", "", "", "yes"),
    Content(" حذاء ", "assets/clothes/shoes-m.png", "yes", "", "", "yes"),
    Content(" كوت ", "assets/clothes/Coat.png", "yes", "", "", "yes"),
    Content(" كاب ", "assets/clothes/cap.png", "yes", "", "", "yes"),
    Content(" قميص ", "assets/clothes/Shirt.png", "yes", "", "", "yes"),
    Content("حقيبة  ", "assets/clothes/3-m.png", "yes", "", "", "yes"),
    Content("نظارة شمسية  ", "assets/clothes/glass.png", "yes", "", "", "yes"),
    Content(" اكسسوارات ", "assets/clothes/1-m.png", "yes", "", "", "yes"),
    Content(
        "ملابس ملونه ", "assets/clothes/clothes-m.png", "yes", "", "", "yes"),
  ]),
  lib("افعال", "assets/actions/0.png", "yes", [
    Content("قبله", "assets/actions/1.png", "yes", "", "", "yes"),
    Content("فكرة", "assets/actions/2.png", "yes", "", "", "yes"),
    Content("ضحك", "assets/actions/3.jpg", "yes", "", "", "yes"),
    Content("لعق", "assets/actions/4.png", "yes", "", "", "yes"),
    Content("تذكر", "assets/actions/5.png", "yes", "", "", "yes"),
    Content("غضب", "assets/actions/6.jpg", "yes", "", "", "yes"),
    Content("كابوس", "assets/actions/7.png", "yes", "", "", "yes"),
    Content("عض", "assets/actions/8.png", "yes", "", "", "yes"),
    Content("سعال", "assets/actions/9.png", "yes", "", "", "yes"),
    Content("يتحدث", "assets/actions/10.png", "yes", "", "", "yes"),
    Content("ينظر", "assets/actions/11.png", "yes", "", "", "yes"),
    Content("تنظر", "assets/actions/12.png", "yes", "", "", "yes"),
    Content("الم", "assets/actions/13.png", "yes", "", "", "yes"),
  ]),
  lib("وسائل نقل", "assets/transportation/0.png", "yes", [
    Content("قارب", "assets/transportation/1.png", "yes", "", "", "yes"),
    Content("باص", "assets/transportation/2.png", "yes", "", "", "yes"),
    Content("سيارة اجرة", "assets/transportation/3.png", "yes", "", "", "yes"),
    Content("سيارة", "assets/transportation/4.png", "yes", "", "", "yes"),
    Content("دراجة نارية", "assets/transportation/5.png", "yes", "", "", "yes"),
    Content(
        "سيارة الشرطة", "assets/transportation/6.png", "yes", "", "", "yes"),
    Content("طوافة", "assets/transportation/7.png", "yes", "", "", "yes"),
    Content("طريق", "assets/transportation/8.png", "yes", "", "", "yes"),
    Content("سفينة", "assets/transportation/9.png", "yes", "", "", "yes"),
    Content(
        "سيارة رياضية", "assets/transportation/10.png", "yes", "", "", "yes"),
    Content("شارع", "assets/transportation/11.png", "yes", "", "", "yes"),
    Content("قطار", "assets/transportation/12.png", "yes", "", "", "yes"),
  ]),
  lib("مهن", "assets/careers/0.png", "yes", [
    Content("خباز", "assets/careers/1.jpg", "yes", "", "", "yes"),
    Content("حلاق", "assets/careers/2.jpg", "yes", "", "", "yes"),
    Content("مهنة ", "assets/careers/3.png", "yes", "", "", "yes"),
    Content("شرطي", "assets/careers/4.png", "yes", "", "", "yes"),
    Content("مديرة", "assets/careers/5.png", "yes", "", "", "yes"),
    Content("دكتورة", "assets/careers/6.png", "yes", "", "", "yes"),
    Content("سائق", "assets/careers/7.png", "yes", "", "", "yes"),
    Content("صباغ", "assets/careers/8.jpg", "yes", "", "", "yes"),
    Content("سباح", "assets/careers/9.png", "yes", "", "", "yes"),
    Content("معلم/ة", "assets/careers/10.png", "yes", "", "", "yes"),
  ]),
  lib("عبادات", "assets/worship/0.png", "yes", [
    Content("عرفة", "assets/worship/1.png", "yes", "", "", "yes"),
    Content("صلاة العصر", "assets/worship/2.png", "yes", "", "", "yes"),
    Content("صلاة الفجر", "assets/worship/4.png", "yes", "", "", "yes"),
    Content("الكعبة", "assets/worship/5.jpg", "yes", "", "", "yes"),
    Content("صلاة ليلة القدر", "assets/worship/6.jpg", "yes", "", "", "yes"),
    Content("دعاء", "assets/worship/7.png", "yes", "", "", "yes"),
    Content("الصلاة", "assets/worship/77.png", "yes", "", "", "yes"),
    Content("صلاة القيام", "assets/worship/8.png", "yes", "", "", "yes"),
    Content("ركوع", "assets/worship/9.png", "yes", "", "", "yes"),
    Content("سجود", "assets/worship/10.png", "yes", "", "", "yes"),
    Content("تكبير", "assets/worship/11.png", "yes", "", "", "yes"),
    Content("التشهد", "assets/worship/12.png", "yes", "", "", "yes"),
    Content("الطواف", "assets/worship/13.png", "yes", "", "", "yes"),
  ]),
  lib("أشكال", "assets/shapes.png", "yes", [
    Content("دائرة  ", "assets/circle.png", "yes", "", "", "yes"),
    Content(" مربع", "assets/square.png", "yes", "", "", "yes"),
    Content("معين", "assets/oval.png", "yes", "", "", "yes"),
    Content("مثلث", "assets/tringle.png", "yes", "", "", "yes"),
    Content("نجمة", "assets/star.png", "yes", "", "", "yes"),
    Content("مستطيل", "assets/rectangle1.png", "yes", "", "", "yes")
  ]),
  lib("اتجاهات", "assets/postions.png", "yes", [
    Content("على  ", "assets/on.png", "yes", "", "", "yes"),
    Content(" مقابل", "assets/front.jpg", "yes", "", "", "yes"),
    Content("أسفل", "assets/down.png", "yes", "", "", "yes"),
    Content("يمين", "assets/right.png", "yes", "", "", "yes"),
    Content("بين", "assets/between.png", "yes", "", "", "yes"),
  ]),
];
